"""Public package surface for `agentos_workflow.orchestrator`.

`WorkflowSession` (`engine.py`) is the sole runtime facade an external caller is meant to hold: it
owns a workflow's `RepositoryLock`, `StateStore`, and `WorkflowStateMachine` together for that
workflow's entire active lifetime and never exposes any of the three directly (`ARCHITECTURE.md`
§2, §5). This module's `__all__` is therefore deliberately narrow — `WorkflowStateMachine`,
`RepositoryLock`, `StateStore`, and the module-level primitives they compose
(`authorize`, `resume_workflow`, `evaluate_repair_attempt`, ...) remain real, independently
importable, independently tested building blocks for lower-level or whitebox use (this package's
own test suite imports them directly), but are not re-exported here as the intended external
surface.
"""

from agentos_workflow.orchestrator.engine import (
    AttemptKind,
    AttemptLimitExceededError,
    AttemptPhase,
    AuthorizationAlreadyPersistedError,
    AuthorizationBindingDriftError,
    AuthorizationBypassError,
    AuthorizationContext,
    AuthorizationError,
    AuthorizationRecord,
    AuthorizationRecordError,
    AuthorizationScopeMismatchError,
    CommitEvidence,
    CorruptedAttemptRecordError,
    CorruptedAuthorizationRecordError,
    CorruptedHistoryError,
    CurrentAuthorizationBinding,
    DuplicateAttemptNumberError,
    EvidenceConsistencyError,
    EvidenceOperationMismatchError,
    EvidenceScopeMismatchError,
    ImplementationDiffEvidence,
    InconsistentAttemptHistoryError,
    InconsistentHistoryError,
    InitialExecutionFailureKind,
    InvalidActorForTransitionError,
    InvalidAttemptNumberError,
    InvalidTransitionError,
    MissingAttemptReservationError,
    MissingAuthorizationError,
    MissingAuthorizationRecordError,
    MissingPersistedStateError,
    MissingReconciliationEvidenceError,
    NotRetryableStateError,
    PullRequestEvidence,
    ReconciliationEvidence,
    RemoteRefEvidence,
    RepositoryLockIdentityMismatchError,
    RepositoryLockUnavailableError,
    ResumeError,
    ResumeReconciliationRequiredError,
    RetryAttemptRecord,
    RetryError,
    RetryOutcome,
    RetryReconciliationResult,
    SkippedAttemptNumberError,
    UnexpectedWorkflowStateError,
    UnreconciledAttemptError,
    WorkflowAlreadyTerminalError,
    WorkflowIdReuseError,
    WorkflowSession,
    WorkflowSessionError,
    WorkflowStageMismatchError,
    WorkflowState,
)
from agentos_workflow.orchestrator.lock import LockContentionError, LockError, LockStateError
from agentos_workflow.orchestrator.state_store import StateStoreCorruptionError, StateStoreError

__all__ = [
    "AttemptKind",
    "AttemptLimitExceededError",
    "AttemptPhase",
    "AuthorizationAlreadyPersistedError",
    "AuthorizationBindingDriftError",
    "AuthorizationBypassError",
    "AuthorizationContext",
    "AuthorizationError",
    "AuthorizationRecord",
    "AuthorizationRecordError",
    "AuthorizationScopeMismatchError",
    "CommitEvidence",
    "CorruptedAttemptRecordError",
    "CorruptedAuthorizationRecordError",
    "CorruptedHistoryError",
    "CurrentAuthorizationBinding",
    "DuplicateAttemptNumberError",
    "EvidenceConsistencyError",
    "EvidenceOperationMismatchError",
    "EvidenceScopeMismatchError",
    "ImplementationDiffEvidence",
    "InconsistentAttemptHistoryError",
    "InconsistentHistoryError",
    "InitialExecutionFailureKind",
    "InvalidActorForTransitionError",
    "InvalidAttemptNumberError",
    "InvalidTransitionError",
    "LockContentionError",
    "LockError",
    "LockStateError",
    "MissingAttemptReservationError",
    "MissingAuthorizationError",
    "MissingAuthorizationRecordError",
    "MissingPersistedStateError",
    "MissingReconciliationEvidenceError",
    "NotRetryableStateError",
    "PullRequestEvidence",
    "ReconciliationEvidence",
    "RemoteRefEvidence",
    "RepositoryLockIdentityMismatchError",
    "RepositoryLockUnavailableError",
    "ResumeError",
    "ResumeReconciliationRequiredError",
    "RetryAttemptRecord",
    "RetryError",
    "RetryOutcome",
    "RetryReconciliationResult",
    "SkippedAttemptNumberError",
    "StateStoreCorruptionError",
    "StateStoreError",
    "UnexpectedWorkflowStateError",
    "UnreconciledAttemptError",
    "WorkflowAlreadyTerminalError",
    "WorkflowIdReuseError",
    "WorkflowSession",
    "WorkflowSessionError",
    "WorkflowStageMismatchError",
    "WorkflowState",
]
